Rubocop rules from insights-api-common + yamllint
RedHatInsights/topological_inventory-persister pull request #77
Opened 2020-10-29 15:56 UTC by slemrmartin

Because of https://github.com/ManageIQ/guides/pull/443 rubocop rules were moved to another repo. 
So we are moving the file to our common repo.

* [x] depends on https://github.com/RedHatInsights/insights-api-common-rails/pull/211

---

[RHCLOUD-10237](https://issues.redhat.com/browse/RHCLOUD-10237)

2020-10-29 19:51 UTC, lindgrenj6 requested changes
We probably want to pull out the openapi jar files for this.

2020-10-30 08:42 UTC, slemrmartin commented
@lindgrenj6 I don't understand how your comment relates to this PR. JAR files are in gitignore

2020-10-30 08:54 UTC, slemrmartin commented
ha, I see it, I don't know how it happened

2020-10-30 14:32 UTC, lindgrenj6 approved these changes

2020-10-30 14:32 UTC, merged